### PR TITLE
add proxy env variables to all Dockerfiles

### PR DESCRIPTION
**Pull request by alexsedova**
Add env, variables. While I dont have proxy, they are setting by empty fields. The env are available in docker containers. I wanted to do it by one shell config file, but it seems tricky - still need to be investigated. About proxy variable. Should I set in low case and in high case in the same time, is it any difference ?

### CODE REVIEW

**Comment by Andrey9kin** [comment]
@alexsedova I'm not sure about lower case you need to look it up. Please remove empty line that you added to docker-compose.yml and reference the issue in the commit message

**Comment by alexsedova** [comment]
Lines just removed)

**Comment by alexsedova** [comment]
As I understood proxy variables could be in both cases and they are not the same. I mean http_proxy does not match HTTP_PROXY by default. In some cases variables could be low cased in others high, it depends on administrator who set their. If my vision is correct)  Ok I investigate it then

**Comment by alexsedova** [comment]
about issue reference, name of the branch is issue reference, should add in commit message reference ?

**Pull request merged**
