### PR TITLE
Fix #87: Support for scaling containers

### LINKED ISSUE #87: Support for scaling containers
e.g. by adding

> docker-compose -p dockerizeit scale jslave=5

to the  bootstrap.sh

### PR DESCRIPTION
**Pull request by drBosse**

### CODE REVIEW

**Comment by Andrey9kin** [comment]
@drBosse what is the problem that we are trying to address here?

**Comment by drBosse** [comment]
To enable scaling the number of slaves
if you do that the review will crash when it get multiple answers in the docker ps call in get_binds

**Comment by Andrey9kin** [comment]
@drBosse we can merge this one, however we never intended to have more than one utility slave. If users need more slaves like that then they should update docker compose file to make a copy and name it differently. That copy could be scaled as much as they like

**Comment by Andrey9kin** [comment]
@drBosse i think there is no need in this one any longer. Closing it now. Please feel free to reopen if it is needed

**Pull request closed without merging**
